- name: Set Fedora Variables
  when: ansible_facts['distribution'] == "Fedora"
  include_vars: "vars/Fedora.yml"

- name: Install Packages
  when: nvim_packages is defined
  package:
    name: "{{ nvim_packages }}"
    state: latest

- name: Remove Packages
  when: nvim_remove_packages is defined
  package:
    name: "{{ nvim_remove_packages }}"
    state: absent

- name: Install csh Default Editor Script
  copy:
    src: files/nvim-default-editor.csh
    dest: /etc/profile.d/nvim-default-editor.csh
    mode: 0644
    owner: root

- name: Install sh Default Editor Script
  copy:
    src: files/nvim-default-editor.sh
    dest: /etc/profile.d/nvim-default-editor.sh
    mode: 0644
    owner: root
