- name: Base Configuration
  hosts: all
  become: no
  tasks:
  - name: ping
    when: ansible_os_family != "Windows"
    ansible.builtin.ping:

  - name: win_ping
    when: ansible_os_family == "Windows"
    ansible.builtin.win_ping:
