ungrouped:

linux_hosts:
  hosts:
    desk:
      ansible_host: 192.168.0.28
    test:
      ansible_host: 192.168.0.35

linux_servers:
  hosts:

linux_workstations:
  hosts:
    desk
    test

week_1_update:
  children:

