- name: Add Trusted Certificates to Gentoo and Debian/Ubuntu
  copy:
    src: "{{ item }}"
    dest: /usr/local/share/ca-certificates/
    owner: root
    group: root
    mode: "0644"
    backup: no
  loop: "{{ ca_certs }}"

- name: Import Certs
  command: update-ca-certificates
