- name: Add Trusted Certificates to Arch and Manjaro
  copy:
    src: "{{ item }}"
    dest: /etc/ca-certificates/trust-source/anchors
    owner: root
    group: root
    mode: "0644"
    backup: no
  loop: "{{ ca_certs }}"

- name: Import Certs
  command: trust extract-compat
