- name: Set Fedora Variables
  when: ansible_facts['distribution'] == "Fedora"
  include_vars: "vars/Fedora.yml"

- name: Remove Packages
  when: kde_remove_packages is defined
  package:
    name: "{{ kde_remove_packages }}"
    state: absent

- name: Install Packages
  when: kde_install_packages is defined
  package:
    name: "{{ kde_install_packages }}"
    state: latest

- name: Create Fonts Directory
  file:
    state: directory
    path: /usr/share/fonts/acmelabs

- name: Install Fonts
  copy:
    src: "{{ item }}"
    dest: /usr/share/fonts/acmelabs
    owner: root
    group: root
    mode: "0644"
    backup: no
  loop:
    - "HackNerdFont-Regular.ttf"
    - "HackNerdFont-Bold.ttf"
    - "HackNerdFont-Italic.ttf"
    - "HackNerdFont-BoldItalic.ttf"
    - "HackNerdFontMono-Regular.ttf"
    - "HackNerdFontMono-Bold.ttf"
    - "HackNerdFontMono-Italic.ttf"
    - "HackNerdFontMono-BoldItalic.ttf"
    - "HackNerdFontPropo-Regular.ttf"
    - "HackNerdFontPropo-Bold.ttf"
    - "HackNerdFontPropo-Italic.ttf"
    - "HackNerdFontPropo-BoldItalic.ttf"

