install_packages:
  - git
  - tmux
  - openssh-server
backup_files:
  - "/etc/tmux.conf"
config_files:
  - { src: "99-custom.sh", path: "/etc/profile.d/99-custom.sh" }
  - { src: "tmux.conf", path: "/etc/tmux.conf" }
  - { src: "tmuxline.conf", path: "/etc/tmuxline.conf" }
