config_files:
  - { state: link, src: "/usr/share/acmelabs/config_files/bashrc-manjaro", path: ".bashrc" }
  - { state: link, src: "/usr/share/acmelabs/config_files/tmux.conf", path: ".tmux.conf" }
  - { state: link, src: "/usr/share/acmelabs/config_files/promptline.sh", path: ".promptline.sh" }
  - { state: link, src: "/usr/share/acmelabs/config_files/tmuxline.sh", path: ".tmuxline.sh" }
