ungrouped:

linux_hosts:
  hosts:
    #3cx:
    #  ansible_host: priefert.my3cx.us
    #ansible:
    #  ansible_host: ansible.ad.priefert.com
    bareos:
      ansible_host: bareos.mtp.priefert.com
    bcarter-fedora:
      ansible_host: bcarter-fedora.ad.priefert.com
    cybadmin-2:
      ansible_host: 172.18.2.115
    gitlab:
      ansible_host: gitlab.priefert.com
    frame:
      ansible_host: 172.17.4.69
    kalvarado-linux:
      ansible_host: 172.18.2.123
    #nfs:
    #  ansible_host: nfs.ad.priefert.com
    nessus:
      ansible_host: nessus.priefert.com
    #pureback:
    #  ansible_host: pureback.ad.priefert.com
    relay:
      ansible_host: relay.ad.priefert.com
    #sftp:
    #  ansible_host: sftp.ad.priefert.com

linux_servers:
  hosts:
    bareos:
    gitlab:
    nessus:
    relay:

linux_workstations:
  hosts:
    cybadmin-2:
    frame:
    kalvarado-linux:

windows_hosts:
  hosts:
    apollo:
      ansible_host: apollo.ad.priefert.com
    axbatch1:
      ansible_host: axbatch1.ad.priefert.com
    axbatch2:
      ansible_host: axbatch2.ad.priefert.com
    axdev:
      ansible_host: axdev.ad.priefert.com
    axsanjeevd:
      ansible_host: axsanjeevd.ad.priefert.com
    axsjones:
      ansible_host: axsjones.ad.priefert.com
    axtest:
      ansible_host: axtest.ad.priefert.com
    axtrain:
      ansible_host: axtrain.ad.priefert.com
    axzshipp:
      ansible_host: axzshipp.ad.priefert.com
    clickonce:
      ansible_host: clickonce.ad.priefert.com
    dfwsr01:
      ansible_host: dfwsr01.ad.priefert.com
    fuel:
      ansible_host: fuel.ad.priefert.com
    igngateway:
      ansible_host: igngateway.ad.priefert.com
    ir-pmf-001:
      ansible_host: ir-pmf-001.ad.priefert.com
    lab-002-vw:
      ansible_host: lab-002-vw.ad.priefert.com
    maestro:
      ansible_host: maestro.ad.priefert.com
    mktsvr:
      ansible_host: mktsvr.ad.priefert.com
    partner:
      ansible_host: partner.ad.priefert.com
    pcmiler:
      ansible_host: pcmiler.ad.priefert.com
    pm-db-01:
      ansible_host: pm-db-01.ad.priefert.com
    pm-db-02:
      ansible_host: pm-db-02.ad.priefert.com
    pm-db-03:
      ansible_host: pm-db-03.ad.priefert.com
    pm-db-dev:
      ansible_host: pm-db-dev.ad.priefert.com

windows_servers:
  hosts:
    apollo:
    axbatch1:
    axbatch2:
    axdev:
    axsanjeevd:
    axsjones:
    axtest:
    axtrain:
    axzshipp:
    clickonce:
    dfwsr01:
    fuel:
    igngateway:
    ir-pmf-001:
    maestro:
    mktsvr:
    partner:
    pcmiler:
    pm-db-01:
    pm-db-02:
    pm-db-03:
    pm-db-dev:

windows_workstations:
  hosts:
    lab-002-vw:

week_1_update:
  children:

