ungrouped:

linux_hosts:
  hosts:
    #3cx:
    #  ansible_host: priefert.my3cx.us
    #ansible:
    #  ansible_host: ansible.ad.priefert.com
    bareos:
      ansible_host: bareos.mtp.priefert.com
    bcarter-fedora:
      ansible_host: bcarter-fedora.ad.priefert.com
    #gitlab:
    #  ansible_host: gitlab.priefert.com
    #nfs:
    #  ansible_host: nfs.ad.priefert.com
    #pureback:
    #  ansible_host: pureback.ad.priefert.com
    relay:
      ansible_host: relay.ad.priefert.com
    #sftp:
    #  ansible_host: sftp.ad.priefert.com

linux_servers:
  hosts:
    bareos
    relay

week_1_update:
  children:

