ungrouped:

ax_servers:
  children:
    ax_prod_servers:
    ax_dev_servers:

ax_prod_servers:
  hosts:
    axbatch1:
    axbatch2:
    axmiler:
    axprod:

ax_dev_servers:
  hosts:
    axdev:
    axggoebel:
    axsanjeevd:
    axsjones:
    axtest:
    axtrain:
    axzshipp:

backup_servers:
  hosts:
    bareos:

database_servers:
  children:
    database_prod:
    database_dev:

database_prod:
  hosts:
    pm-db-01:
    pm-db-02:
    ravendb:

database_dev:
  hosts:
    pm-db-03:
    pm-db-dev:

file_servers:
  hosts:
    mktsvr:
    vault:
    vm-fs-01:
    vm-fs-02:
    vm-fs-03:
    vm-lab-target:

linux_hosts:
  hosts:
  children:
    linux_servers:
    linux_workstations:

linux_servers:
  hosts:
    #3cx:
    #  ansible_host: priefert.my3cx.us
    #ansible:
    #  ansible_host: ansible.ad.priefert.com
    bareos:
      ansible_host: bareos.mtp.priefert.com
    gitlab:
      ansible_host: gitlab.priefert.com
    #nfs:
    #  ansible_host: nfs.ad.priefert.com
    nessus:
      ansible_host: nessus.priefert.com
    #pureback:
    #  ansible_host: pureback.ad.priefert.com
    relay:
      ansible_host: relay.ad.priefert.com
    #sftp:
    #  ansible_host: sftp.ad.priefert.com

linux_workstations:
  hosts:
    bcarter-fedora:
      ansible_host: bcarter-fedora.ad.priefert.com
    cybadmin-2:
      ansible_host: 172.18.2.115
    frame:
      ansible_host: 172.17.4.69
    kalvarado-linux:
      ansible_host: 172.18.2.123

netadmin:
  hosts:
    cybsec-001:

windows_hosts:
  hosts:
  children:
    windows_servers:
    windows_workstations:

windows_servers:
  hosts:
    apollo:
      ansible_host: apollo.ad.priefert.com
    axbatch1:
      ansible_host: axbatch1.ad.priefert.com
    axbatch2:
      ansible_host: axbatch2.ad.priefert.com
    axdev:
      ansible_host: axdev.ad.priefert.com
    axsanjeevd:
      ansible_host: axsanjeevd.ad.priefert.com
    axsjones:
      ansible_host: axsjones.ad.priefert.com
    axtest:
      ansible_host: axtest.ad.priefert.com
    axtrain:
      ansible_host: axtrain.ad.priefert.com
    axzshipp:
      ansible_host: axzshipp.ad.priefert.com
    clickonce:
      ansible_host: clickonce.ad.priefert.com
    cybsec-001:
      ansible_host: cybsec-001.ad.priefert.com
    dfwsr01:
      ansible_host: dfwsr01.ad.priefert.com
    fuel:
      ansible_host: fuel.ad.priefert.com
    pm-hv-01:
      ansible_host: pm-hv-01.ad.priefert.com
    pm-hv-02:
      ansible_host: pm-hv-02.ad.priefert.com
    igngateway:
      ansible_host: igngateway.ad.priefert.com
    ir-pmf-001:
      ansible_host: ir-pmf-001.ad.priefert.com
    maestro:
      ansible_host: maestro.ad.priefert.com
    mktsvr:
      ansible_host: mktsvr.ad.priefert.com
    partner:
      ansible_host: partner.ad.priefert.com
    pcmiler:
      ansible_host: pcmiler.ad.priefert.com
    pm-db-01:
      ansible_host: pm-db-01.ad.priefert.com
    pm-db-02:
      ansible_host: pm-db-02.ad.priefert.com
    pm-db-03:
      ansible_host: pm-db-03.ad.priefert.com
    pm-db-dev:
      ansible_host: pm-db-dev.ad.priefert.com
    printprod:
      ansible_host: printprod.ad.priefert.com
    printserver:
      ansible_host: printserver.ad.priefert.com
    process:
      ansible_host: process.ad.priefert.com
    prtg:
      ansible_host: prtg.ad.priefert.com
    ravendb:
      ansible_host: ravendb.ad.priefert.com
    riverlogic:
      ansible_host: riverlogic.ad.priefert.com
    shopdata:
      ansible_host: shopdata.ad.priefert.com
    trumpf:
      ansible_host: trumpf.ad.priefert.com
    vault:
      ansible_host: vault.ad.priefert.com
    vm-candice:
      ansible_host: vm-candice.ad.priefert.com
    vm-fs-01:
      ansible_host: vm-fs-01.ad.priefert.com
    vm-fs-02:
      ansible_host: vm-fs-02.ad.priefert.com
    vm-fs-03:
      ansible_host: vm-fs-03.ad.priefert.com
    vm-lab-target:
      ansible_host: vm-lab-target.ad.priefert.com
    vsync:
      ansible_host: vsync.ad.priefert.com

windows_workstations:
  hosts:
    lab-002-vw:
      ansible_host: lab-002-vw.ad.priefert.com

update:
  hosts:
  children:

